//go:build integration

// This file is generated by VectorSigma v1.2.0-2-ga04e9e8 (commit: a04e9e8, built at: 2025-12-26T03:11:46Z.1.0). DO NOT EDIT.
package fsm_test

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes/scheme"
	"k8s.io/client-go/rest"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/envtest"

	bifrostv1alpha1 "github.com/peek8/bifrost/api/v1alpha1"
)

var (
	ctx         context.Context
	cancel      context.CancelFunc
	testEnv     *envtest.Environment
	cfg         *rest.Config
	k8sClient   client.Client
	projectroot = filepath.Join("..", "..", "..")

	// Hooks for custom test setup/teardown
	// Add a file to the same package as this file with
	// the following functions to implement custom setup/teardown logic.
	CustomSetupHook    func() error
	CustomTeardownHook func() error
)

var resource = &bifrostv1alpha1.LogSpace{
	TypeMeta: metav1.TypeMeta{
		Kind: kind,
	},
	ObjectMeta: metav1.ObjectMeta{
		Name:      resourceName.Name,
		Namespace: resourceName.Namespace,
	},
}

func setup(t *testing.T) {
	err := k8sClient.Create(context.TODO(), resource)
	require.NoError(t, err)
}

func teardown(t *testing.T) {
	err := k8sClient.Delete(context.TODO(), resource)
	require.NoError(t, err)

	resource = &bifrostv1alpha1.LogSpace{
		TypeMeta: metav1.TypeMeta{
			Kind: kind,
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      resourceName.Name,
			Namespace: resourceName.Namespace,
		},
	}
}

func TestMain(m *testing.M) {
	if err := setupTestEnv(); err != nil {
		fmt.Printf("Test environment setup failed: %v\n", err)
		os.Exit(1)
	}

	exitCode := m.Run()

	if err := teardownTestEnv(); err != nil {
		fmt.Printf("Tear down test environment failed: %v\n", err)
		os.Exit(1)
	}

	os.Exit(exitCode)
}

func setupTestEnv() error {
	ctx, cancel = context.WithCancel(context.TODO())

	// Call custom setup hook if provided
	if CustomSetupHook != nil {
		if err := CustomSetupHook(); err != nil {
			return fmt.Errorf("custom setup failed: %v", err)
		}
	}

	var err error

	err = bifrostv1alpha1.AddToScheme(scheme.Scheme)
	if err != nil {
		return fmt.Errorf("failed to add schema: %v\n", err)
	}

	// +kubebuilder:scaffold:scheme

	testEnv = &envtest.Environment{
		CRDDirectoryPaths:     []string{filepath.Join(projectroot, "config", "crd", "bases")},
		ErrorIfCRDPathMissing: true,
	}

	// Retrieve the first found binary directory to allow running tests from IDEs
	if getFirstFoundEnvTestBinaryDir() != "" {
		testEnv.BinaryAssetsDirectory = getFirstFoundEnvTestBinaryDir()
	}

	// cfg is defined in this file globally.
	cfg, err = testEnv.Start()
	if err != nil {
		return fmt.Errorf("failed to start testenv: %v\n", err)
	}

	k8sClient, err = client.New(cfg, client.Options{Scheme: scheme.Scheme})
	if err != nil {
		return fmt.Errorf("failed to create test client: %v\n", err)
	}

	return nil
}

func teardownTestEnv() error {
	cancel()
	err := testEnv.Stop()
	if err != nil {
		return fmt.Errorf("failed to stop testenv: %v\n", err)
	}

	// Call custom teardown hook if provided
	if CustomTeardownHook != nil {
		if err := CustomTeardownHook(); err != nil {
			return fmt.Errorf("custom teardown failed: %v", err)
		}
	}

	return nil
}

// getFirstFoundEnvTestBinaryDir locates the first binary in the specified path.
// ENVTEST-based tests depend on specific binaries, usually located in paths set by
// controller-runtime. When running tests directly (e.g., via an IDE) without using
// Makefile targets, the 'BinaryAssetsDirectory' must be explicitly configured.
//
// This function streamlines the process by finding the required binaries, similar to
// setting the 'KUBEBUILDER_ASSETS' environment variable. To ensure the binaries are
// properly set up, run 'make setup-envtest' beforehand.
func getFirstFoundEnvTestBinaryDir() string {
	basePath := filepath.Join(projectroot, "bin", "k8s")
	entries, err := os.ReadDir(basePath)
	if err != nil {
		fmt.Printf("failed to read directory: %v", err)
		return ""
	}
	for _, entry := range entries {
		if entry.IsDir() {
			return filepath.Join(basePath, entry.Name())
		}
	}
	return ""
}
